"use strict";
exports.__esModule = true;
var express = require("express");
var radixdlt_1 = require("radixdlt");
var app = express();
var port = 3000;
var ALPHANET = radixdlt_1.RadixUniverse.ALPHANET;
radixdlt_1.radixUniverse.bootstrap(ALPHANET);
var identityManager = new radixdlt_1.RadixIdentityManager();
this.myIdentity = identityManager.generateSimpleIdentity();
var myAccount = this.myIdentity.account;
myAccount.openNodeConnection();
console.log('My address: ', myAccount.getAddress());
app.get('/', function (req, res) { return res.send("My address is " + myAccount.getAddress()); });
app.get('/balance', function (req, res) { return res.send(myAccount.transferSystem.balance); });
app.get('/transfers', function (req, res) { return res.send(myAccount.transferSystem.transactions); });
app.listen(port, function () { return console.log("Example app listening on port " + port + "!"); });
